## agent-related
agent:
  device: "cuda"
  gamma: 0.99 # discount_factor
  r_unav: -1
  epsilon: 0.1
  memory_capacity: 10000
  exploration:
    active: False
    eps_max: 0.8
    eps_min: 0.1
    n_star: 20000

## trainer-related
trainer:
  expert:
    active: True
    epsilon: 0.5
  batch_size: 64
  target_update: 500 # update interval
  val_interval: 250

## scheduler (TODO: test)
lr_scheduler:
  active: False
  name: ONE_CYCLE_LR
  poly_cfg:
    power: 0.9
    max_epochs: 2000
    target_lr: 5.0e-04
  one_cycle_lr_cfg:
    pct_start: 0.05
    final_div_factor: 2
